# Generated by Django 4.0.9 on 2023-03-19 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0037_post_1_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='multiplier',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Arbeitseinsatz vielfaches'),
        ),
    ]
