# Generated by Django 4.0.10 on 2023-09-18 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0040_post_1_6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='creation_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Erzeugt am'),
        ),
    ]
